const express = require('express');
const route = express.Router()
const fromAuthenticate = require('../modules/authenticate')
const fromRegistration = require('../modules/registration')
const fromMail = require('../modules/mail')

route.get('/',fromRegistration.Start)
route.post('/login',fromAuthenticate.Login)
route.post('/register',fromRegistration.Register)
route.get('/verify/:id',fromAuthenticate.EmailVerify)
route.put('/forgetpassword',fromAuthenticate.Forgetpassword)
route.get('/forgetpassword/verify/:id',fromAuthenticate.ForgetPasswordVerify)
route.post('/savepassword/:id',fromAuthenticate.savePassword)
route.post('/send',fromMail.SendMail)
route.get('/inbox/modify/:id',fromMail.InboxModify)
route.get('/sent/modify/:id',fromMail.SentModify)
route.get('/starred/modify/:id',fromMail.StarredModify)
route.get('/inbox/:id',fromMail.Inbox)
route.post('/inbox/bin/:id',fromMail.deleteFromInbox)
route.post('/sent/bin/:id',fromMail.deleteFromSentMail)
route.post('/draft/bin/:id',fromMail.deleteFromDraft)
route.post('/starred/bin/:id',fromMail.deleteFromStarred)
route.post('/delete/:id',fromMail.PermanentDelete)
route.patch('/starred/:id',fromMail.StarredMsg)
route.patch('/unstarred/:id',fromMail.UnStarredMsg)
route.patch('/sent/starred/:id',fromMail.StarredMsg_Sentbox)
route.patch('/sent/unstarred/:id',fromMail.UnStarredMsg_Sentbox)
route.get('/allread/:id',fromMail.Allread)
route.get('/allunread/:id',fromMail.Allunread)
route.patch('/restore/:id',fromMail.RestoreAll)
route.patch('/draft/:id',fromMail.Draft)

module.exports = route